// data.js
// Source data for the Fursa seed script. Each organization maps to a real
// `users` row (role = 'organization') and a real `organizations` row.
// Each opportunity maps to a real `opportunities` row. Categories are
// constrained to the actual enum: 'job' | 'internship' | 'scholarship'.
// The more specific "program type" (e.g. Fellowship, Graduate Trainee)
// is carried in `programType` and folded into the title/description,
// since the schema has no column for it.

const ORGANIZATIONS = [
  {
    key: 'zenith',
    name: 'Zenith Technologies Kenya',
    type: 'company', // Technology Company
    sector: 'Technology',
    email: 'careers@zenithtech.co.ke',
    website: 'https://www.zenithtech.co.ke',
    location: 'Westlands, Nairobi',
    description:
      'Zenith Technologies Kenya is a fast-growing software and cloud engineering company building digital products for banks, telcos, and public-sector clients across East Africa. The company runs engineering, data, and product teams out of its Nairobi headquarters and partners with regional universities on internship and graduate-trainee pipelines.',
  },
  {
    key: 'equitytrust',
    name: 'Equity Trust Bank',
    type: 'company', // Bank
    sector: 'Banking & Finance',
    email: 'talent@equitytrustbank.co.ke',
    website: 'https://www.equitytrustbank.co.ke',
    location: 'Upper Hill, Nairobi',
    description:
      'Equity Trust Bank is a leading retail and corporate bank offering personal banking, SME financing, and digital payments across Kenya. Its graduate and internship programs feed directly into functions including credit risk, IT audit, retail banking, and digital channels.',
  },
  {
    key: 'moict',
    name: 'Ministry of ICT Innovation',
    type: 'government',
    sector: 'Government',
    email: 'internships@ict.go.ke',
    website: 'https://www.ict.go.ke',
    location: 'Harambee Avenue, Nairobi',
    description:
      'The Ministry of ICT Innovation coordinates national digital transformation initiatives, including e-government platforms, digital literacy programs, and ICT policy. The Ministry runs structured internship attachments for students in computer science, public policy, and communications.',
  },
  {
    key: 'globalrelief',
    name: 'Global Relief International',
    type: 'ngo', // International NGO
    sector: 'International NGO',
    email: 'ke-recruitment@globalreliefintl.org',
    website: 'https://www.globalreliefintl.org',
    location: 'Gigiri, Nairobi',
    description:
      'Global Relief International is a multinational humanitarian organization delivering food security, health, and emergency response programs across the Horn of Africa. Its Nairobi regional office runs fellowships and volunteer placements for students in public health, logistics, and monitoring & evaluation.',
  },
  {
    key: 'amani',
    name: 'Amani Community Foundation',
    type: 'ngo', // Local NGO
    sector: 'Local NGO',
    email: 'hr@amanifoundation.or.ke',
    website: 'https://www.amanifoundation.or.ke',
    location: 'Kisumu, Kenya',
    description:
      'Amani Community Foundation is a Kenyan-registered non-profit working on youth empowerment, girls\' education, and community health in Nyanza and Western Kenya. The Foundation offers volunteer and attachment opportunities for students in social work, education, and public health.',
  },
  {
    key: 'nit',
    name: 'Nairobi Institute of Technology',
    type: 'university',
    sector: 'University',
    email: 'careers@nit.ac.ke',
    website: 'https://www.nit.ac.ke',
    location: 'Ngong Road, Nairobi',
    description:
      'Nairobi Institute of Technology is a private university offering degree programs in engineering, computing, and business. The Institute runs research assistantships and teaching-assistant fellowships for high-performing undergraduate and graduate students.',
  },
  {
    key: 'kiar',
    name: 'Kenya Institute for Applied Research',
    type: 'company', // private research institute (no dedicated enum value)
    sector: 'Research Institution',
    email: 'fellowships@kiar.or.ke',
    website: 'https://www.kiar.or.ke',
    location: 'Kabete, Nairobi',
    description:
      'The Kenya Institute for Applied Research is an independent research institute producing policy-relevant research in agriculture, economics, and public health. KIAR hosts research fellowships and data-focused internships for students pursuing statistics, economics, and the sciences.',
  },
  {
    key: 'safarilink',
    name: 'Safarilink Telecommunications',
    type: 'company', // Telecommunications
    sector: 'Telecommunications',
    email: 'graduates@safarilinktel.co.ke',
    website: 'https://www.safarilinktel.co.ke',
    location: 'Nyayo Highrise, Nairobi',
    description:
      'Safarilink Telecommunications is a national telecommunications operator providing mobile, broadband, and enterprise connectivity services. Its network engineering and digital innovation teams run internship and graduate-trainee programs each year.',
  },
  {
    key: 'meridian',
    name: 'Meridian Consulting Group',
    type: 'company', // Consulting Firm
    sector: 'Consulting',
    email: 'recruiting@meridianconsulting.co.ke',
    website: 'https://www.meridianconsulting.co.ke',
    location: 'Kilimani, Nairobi',
    description:
      'Meridian Consulting Group is a management and technology consulting firm advising banks, telcos, and public agencies on strategy, risk, and digital transformation. The firm recruits analysts and interns from top business and IT programs across the region.',
  },
  {
    key: 'eadp',
    name: 'East Africa Development Partnership',
    type: 'ngo', // International Organization
    sector: 'International Organization',
    email: 'opportunities@eadp.org',
    website: 'https://www.eadp.org',
    location: 'UN Avenue, Gigiri, Nairobi',
    description:
      'The East Africa Development Partnership is a regional intergovernmental-adjacent organization coordinating trade, infrastructure, and sustainability programs across East African member states. EADP runs competitive fellowships and innovation challenges for students and young professionals.',
  },
];

// Shared skill/interest pools reused across opportunities and mapped to tags.
const SKILL_POOL = [
  'Java', 'Python', 'React', 'Next.js', 'Node.js', 'Express.js', 'PostgreSQL', 'SQL',
  'Machine Learning', 'Artificial Intelligence', 'Data Analytics', 'Business Analysis',
  'Cloud Computing', 'AWS', 'Azure', 'Cybersecurity', 'Networking', 'Linux',
  'UI/UX Design', 'Project Management', 'Financial Analysis', 'Digital Marketing',
  'Graphic Design', 'Communication', 'Leadership',
];

const INTEREST_POOL = [
  'Artificial Intelligence', 'Data Science', 'Software Engineering', 'Cloud Computing',
  'Cybersecurity', 'Mobile Development', 'Web Development', 'Accounting', 'Auditing',
  'Finance', 'Economics', 'Healthcare', 'Research', 'Robotics', 'Sustainability',
  'Renewable Energy', 'Education', 'Agriculture', 'Entrepreneurship', 'Public Policy',
];

// Five opportunities per organization. `category` must be one of
// 'job' | 'internship' | 'scholarship'. `minEducation` and `minGrade`
// must match the DB enums exactly.
const OPPORTUNITIES = {
  zenith: [
    { programType: 'Software Engineering Internship', category: 'internship', discipline: 'Computer Science / Software Engineering',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Java', 'React', 'Node.js', 'SQL', 'Cloud Computing', 'Communication'],
      interests: ['Software Engineering', 'Web Development', 'Cloud Computing'],
      deadlineDays: 45, minimumMatchScore: 55 },
    { programType: 'Graduate Trainee Program - Cloud Engineering', category: 'job', discipline: 'Information Technology / Cloud Computing',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['AWS', 'Azure', 'Linux', 'Networking', 'Cloud Computing', 'Project Management'],
      interests: ['Cloud Computing', 'Software Engineering'],
      deadlineDays: 60, minimumMatchScore: 60 },
    { programType: 'Data Analytics Internship', category: 'internship', discipline: 'Data Science / Statistics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Python', 'SQL', 'Data Analytics', 'Machine Learning', 'Communication'],
      interests: ['Data Science', 'Artificial Intelligence'],
      deadlineDays: 30, minimumMatchScore: 50 },
    { programType: 'Cybersecurity Attachment', category: 'internship', discipline: 'Information Technology / Cybersecurity',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Cybersecurity', 'Networking', 'Linux', 'Communication'],
      interests: ['Cybersecurity', 'Software Engineering'],
      deadlineDays: 40, minimumMatchScore: 50 },
    { programType: 'Innovation Challenge - Fintech Solutions', category: 'job', discipline: 'Computer Science / Fintech',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Python', 'React', 'Machine Learning', 'Project Management', 'Leadership'],
      interests: ['Software Engineering', 'Finance', 'Entrepreneurship'],
      deadlineDays: 75, minimumMatchScore: 45 },
  ],
  equitytrust: [
    { programType: 'IT Audit Graduate Trainee Program', category: 'job', discipline: 'Accounting / Information Systems',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Financial Analysis', 'SQL', 'Cybersecurity', 'Project Management', 'Communication'],
      interests: ['Auditing', 'Finance', 'Cybersecurity'],
      deadlineDays: 50, minimumMatchScore: 60 },
    { programType: 'Retail Banking Internship', category: 'internship', discipline: 'Business / Banking & Finance',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Financial Analysis', 'Communication', 'Business Analysis'],
      interests: ['Finance', 'Economics'],
      deadlineDays: 35, minimumMatchScore: 45 },
    { programType: 'Digital Channels & Data Analytics Internship', category: 'internship', discipline: 'Information Technology / Data Science',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['SQL', 'Python', 'Data Analytics', 'UI/UX Design'],
      interests: ['Data Science', 'Finance'],
      deadlineDays: 40, minimumMatchScore: 55 },
    { programType: 'Credit Risk Scholarship', category: 'scholarship', discipline: 'Economics / Finance / Actuarial Science',
      minEducation: 'undergraduate', minGrade: 'first_class', minExperience: 0,
      skills: ['Financial Analysis', 'Data Analytics', 'Communication'],
      interests: ['Finance', 'Economics'],
      deadlineDays: 90, minimumMatchScore: 65 },
    { programType: 'Entry-Level Software Developer', category: 'job', discipline: 'Computer Science / Software Engineering',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 1,
      skills: ['Java', 'SQL', 'Node.js', 'Cybersecurity'],
      interests: ['Software Engineering', 'Finance'],
      deadlineDays: 55, minimumMatchScore: 55 },
  ],
  moict: [
    { programType: 'E-Government Systems Internship', category: 'internship', discipline: 'Computer Science / Public Policy',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['SQL', 'Project Management', 'Communication', 'Networking'],
      interests: ['Public Policy', 'Software Engineering'],
      deadlineDays: 40, minimumMatchScore: 45 },
    { programType: 'Digital Literacy Volunteer Position', category: 'internship', discipline: 'Education / Communications',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Communication', 'Leadership', 'Digital Marketing'],
      interests: ['Education', 'Public Policy'],
      deadlineDays: 25, minimumMatchScore: 35 },
    { programType: 'ICT Policy Research Attachment', category: 'internship', discipline: 'Public Policy / Economics',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Business Analysis', 'Communication', 'Data Analytics'],
      interests: ['Public Policy', 'Research'],
      deadlineDays: 45, minimumMatchScore: 50 },
    { programType: 'Cybersecurity Policy Fellowship', category: 'scholarship', discipline: 'Cybersecurity / Public Policy',
      minEducation: 'graduate', minGrade: 'second_upper', minExperience: 1,
      skills: ['Cybersecurity', 'Networking', 'Communication', 'Project Management'],
      interests: ['Cybersecurity', 'Public Policy'],
      deadlineDays: 70, minimumMatchScore: 60 },
    { programType: 'Government Graduate Trainee - Systems Administration', category: 'job', discipline: 'Information Technology',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Linux', 'Networking', 'Cybersecurity', 'Communication'],
      interests: ['Cybersecurity', 'Public Policy'],
      deadlineDays: 60, minimumMatchScore: 45 },
  ],
  globalrelief: [
    { programType: 'Public Health Fellowship', category: 'scholarship', discipline: 'Public Health / Nursing / Medicine',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Data Analytics', 'Communication', 'Project Management'],
      interests: ['Healthcare', 'Research'],
      deadlineDays: 65, minimumMatchScore: 55 },
    { programType: 'Logistics & Supply Chain Internship', category: 'internship', discipline: 'Business / Procurement',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Project Management', 'Business Analysis', 'Communication'],
      interests: ['Sustainability', 'Public Policy'],
      deadlineDays: 30, minimumMatchScore: 40 },
    { programType: 'Monitoring & Evaluation Volunteer Position', category: 'internship', discipline: 'Statistics / Social Sciences',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Data Analytics', 'SQL', 'Communication'],
      interests: ['Research', 'Healthcare'],
      deadlineDays: 35, minimumMatchScore: 40 },
    { programType: 'Emergency Response Attachment', category: 'internship', discipline: 'Public Health / Disaster Management',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Communication', 'Leadership', 'Project Management'],
      interests: ['Healthcare', 'Sustainability'],
      deadlineDays: 20, minimumMatchScore: 35 },
    { programType: 'Data Science for Humanitarian Response Internship', category: 'internship', discipline: 'Data Science / Statistics',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Python', 'Data Analytics', 'Machine Learning'],
      interests: ['Data Science', 'Healthcare'],
      deadlineDays: 50, minimumMatchScore: 50 },
  ],
  amani: [
    { programType: "Girls' Education Volunteer Position", category: 'internship', discipline: 'Education / Social Work',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Communication', 'Leadership'],
      interests: ['Education', 'Public Policy'],
      deadlineDays: 25, minimumMatchScore: 30 },
    { programType: 'Community Health Attachment', category: 'internship', discipline: 'Public Health / Nursing',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Communication', 'Data Analytics'],
      interests: ['Healthcare', 'Education'],
      deadlineDays: 30, minimumMatchScore: 30 },
    { programType: 'Youth Empowerment Program Internship', category: 'internship', discipline: 'Social Work / Communications',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Communication', 'Leadership', 'Digital Marketing'],
      interests: ['Education', 'Entrepreneurship'],
      deadlineDays: 40, minimumMatchScore: 35 },
    { programType: 'Monitoring & Evaluation Volunteer Position', category: 'internship', discipline: 'Statistics / Social Sciences',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Data Analytics', 'Communication'],
      interests: ['Research', 'Education'],
      deadlineDays: 35, minimumMatchScore: 30 },
    { programType: 'Communications & Fundraising Attachment', category: 'internship', discipline: 'Marketing / Communications',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 0,
      skills: ['Digital Marketing', 'Graphic Design', 'Communication'],
      interests: ['Entrepreneurship', 'Education'],
      deadlineDays: 30, minimumMatchScore: 30 },
  ],
  nit: [
    { programType: 'Undergraduate Research Assistantship - AI Lab', category: 'scholarship', discipline: 'Computer Science / Artificial Intelligence',
      minEducation: 'undergraduate', minGrade: 'first_class', minExperience: 0,
      skills: ['Python', 'Machine Learning', 'Artificial Intelligence'],
      interests: ['Artificial Intelligence', 'Research'],
      deadlineDays: 55, minimumMatchScore: 60 },
    { programType: 'Teaching Assistant Fellowship - Software Engineering', category: 'scholarship', discipline: 'Computer Science / Software Engineering',
      minEducation: 'graduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Java', 'Python', 'Communication', 'Leadership'],
      interests: ['Software Engineering', 'Education'],
      deadlineDays: 45, minimumMatchScore: 55 },
    { programType: 'Renewable Energy Systems Research Internship', category: 'internship', discipline: 'Engineering / Environmental Science',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Data Analytics', 'Project Management', 'Communication'],
      interests: ['Sustainability', 'Renewable Energy'],
      deadlineDays: 50, minimumMatchScore: 50 },
    { programType: 'Robotics Innovation Challenge', category: 'job', discipline: 'Engineering / Robotics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Python', 'Machine Learning', 'Project Management'],
      interests: ['Robotics', 'Artificial Intelligence'],
      deadlineDays: 65, minimumMatchScore: 45 },
    { programType: 'University Data Systems Internship', category: 'internship', discipline: 'Information Systems / Statistics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['SQL', 'Data Analytics', 'Cloud Computing'],
      interests: ['Data Science', 'Education'],
      deadlineDays: 30, minimumMatchScore: 40 },
  ],
  kiar: [
    { programType: 'Agricultural Economics Research Fellowship', category: 'scholarship', discipline: 'Economics / Agriculture',
      minEducation: 'graduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Data Analytics', 'Financial Analysis', 'Communication'],
      interests: ['Agriculture', 'Economics', 'Research'],
      deadlineDays: 70, minimumMatchScore: 55 },
    { programType: 'Public Health Statistics Internship', category: 'internship', discipline: 'Statistics / Actuarial Science',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Python', 'SQL', 'Data Analytics'],
      interests: ['Research', 'Healthcare'],
      deadlineDays: 40, minimumMatchScore: 50 },
    { programType: 'Policy Research Attachment', category: 'internship', discipline: 'Public Policy / Economics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Business Analysis', 'Communication', 'Data Analytics'],
      interests: ['Public Policy', 'Research'],
      deadlineDays: 35, minimumMatchScore: 40 },
    { programType: 'Machine Learning for Development Research Fellowship', category: 'scholarship', discipline: 'Data Science / Computer Science',
      minEducation: 'graduate', minGrade: 'first_class', minExperience: 1,
      skills: ['Python', 'Machine Learning', 'Artificial Intelligence', 'Data Analytics'],
      interests: ['Artificial Intelligence', 'Data Science', 'Research'],
      deadlineDays: 80, minimumMatchScore: 65 },
    { programType: 'Environmental Science Field Research Internship', category: 'internship', discipline: 'Environmental Science / Agriculture',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Data Analytics', 'Communication', 'Project Management'],
      interests: ['Sustainability', 'Agriculture', 'Research'],
      deadlineDays: 45, minimumMatchScore: 40 },
  ],
  safarilink: [
    { programType: 'Network Engineering Graduate Trainee Program', category: 'job', discipline: 'Telecommunications / Electrical Engineering',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Networking', 'Linux', 'Cybersecurity', 'Project Management'],
      interests: ['Cybersecurity', 'Software Engineering'],
      deadlineDays: 50, minimumMatchScore: 55 },
    { programType: 'Mobile App Development Internship', category: 'internship', discipline: 'Computer Science / Mobile Development',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['React', 'Node.js', 'UI/UX Design'],
      interests: ['Mobile Development', 'Web Development'],
      deadlineDays: 35, minimumMatchScore: 45 },
    { programType: 'Digital Innovation Challenge - 5G Use Cases', category: 'job', discipline: 'Telecommunications / Innovation',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Python', 'Project Management', 'Leadership'],
      interests: ['Software Engineering', 'Entrepreneurship'],
      deadlineDays: 75, minimumMatchScore: 40 },
    { programType: 'Customer Data Analytics Internship', category: 'internship', discipline: 'Data Science / Marketing',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['SQL', 'Data Analytics', 'Digital Marketing'],
      interests: ['Data Science', 'Entrepreneurship'],
      deadlineDays: 40, minimumMatchScore: 45 },
    { programType: 'Entry-Level Cloud Support Engineer', category: 'job', discipline: 'Information Technology / Cloud Computing',
      minEducation: 'diploma', minGrade: 'pass', minExperience: 1,
      skills: ['AWS', 'Linux', 'Networking', 'Communication'],
      interests: ['Cloud Computing', 'Cybersecurity'],
      deadlineDays: 45, minimumMatchScore: 40 },
  ],
  meridian: [
    { programType: 'Management Consulting Graduate Trainee Program', category: 'job', discipline: 'Business Analysis / Strategy',
      minEducation: 'undergraduate', minGrade: 'first_class', minExperience: 0,
      skills: ['Business Analysis', 'Project Management', 'Communication', 'Leadership'],
      interests: ['Entrepreneurship', 'Finance'],
      deadlineDays: 60, minimumMatchScore: 60 },
    { programType: 'Technology Risk Advisory Internship', category: 'internship', discipline: 'Information Systems / Auditing',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Cybersecurity', 'Business Analysis', 'Communication'],
      interests: ['Auditing', 'Cybersecurity'],
      deadlineDays: 45, minimumMatchScore: 55 },
    { programType: 'Digital Transformation Analyst Internship', category: 'internship', discipline: 'Information Systems / Business',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Cloud Computing', 'Business Analysis', 'Project Management'],
      interests: ['Software Engineering', 'Entrepreneurship'],
      deadlineDays: 40, minimumMatchScore: 50 },
    { programType: 'HR & People Analytics Internship', category: 'internship', discipline: 'Human Resources / Data Analytics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Data Analytics', 'Communication', 'Business Analysis'],
      interests: ['Research', 'Entrepreneurship'],
      deadlineDays: 30, minimumMatchScore: 40 },
    { programType: 'Entry-Level Business Analyst', category: 'job', discipline: 'Business Analysis / Economics',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 1,
      skills: ['Business Analysis', 'Financial Analysis', 'Communication'],
      interests: ['Finance', 'Economics'],
      deadlineDays: 55, minimumMatchScore: 50 },
  ],
  eadp: [
    { programType: 'Regional Trade Policy Fellowship', category: 'scholarship', discipline: 'Economics / Law / Public Policy',
      minEducation: 'graduate', minGrade: 'second_upper', minExperience: 1,
      skills: ['Business Analysis', 'Communication', 'Project Management'],
      interests: ['Public Policy', 'Economics'],
      deadlineDays: 85, minimumMatchScore: 60 },
    { programType: 'Sustainability Innovation Challenge', category: 'job', discipline: 'Environmental Science / Engineering',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Project Management', 'Data Analytics', 'Leadership'],
      interests: ['Sustainability', 'Renewable Energy'],
      deadlineDays: 70, minimumMatchScore: 45 },
    { programType: 'Infrastructure Finance Internship', category: 'internship', discipline: 'Finance / Economics',
      minEducation: 'undergraduate', minGrade: 'second_upper', minExperience: 0,
      skills: ['Financial Analysis', 'Data Analytics', 'Communication'],
      interests: ['Finance', 'Public Policy'],
      deadlineDays: 45, minimumMatchScore: 50 },
    { programType: 'Regional Data & Statistics Internship', category: 'internship', discipline: 'Statistics / Economics',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['SQL', 'Data Analytics', 'Communication'],
      interests: ['Research', 'Economics'],
      deadlineDays: 40, minimumMatchScore: 40 },
    { programType: 'Youth in Agribusiness Competition', category: 'job', discipline: 'Agriculture / Entrepreneurship',
      minEducation: 'undergraduate', minGrade: 'second_lower', minExperience: 0,
      skills: ['Business Analysis', 'Leadership', 'Communication'],
      interests: ['Agriculture', 'Entrepreneurship'],
      deadlineDays: 60, minimumMatchScore: 40 },
  ],
};

module.exports = { ORGANIZATIONS, OPPORTUNITIES, SKILL_POOL, INTEREST_POOL };
