// @ts-nocheck
'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import ReportModal from "@/components/ReportModal";


export default function AdminOpportunities() {
  const [opps, setOpps] = useState([]);
  const [error, setError] = useState('');
  const [reportOpen, setReportOpen] = useState(false);

  useEffect(() => { load(); }, []);

  const load = async () => {
    try {
      const res = await apiFetch('/api/admin/opportunities');
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to load');
      setOpps(data);
    } catch (err) { setError(err.message); }
  };

  const handleDelete = async (id) => {
    if (!confirm('Are you sure you want to delete this global opportunity?')) return;
    try {
      const res = await apiFetch(`/api/admin/opportunities/${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete');
      setOpps((prev) => prev.filter((o) => o.id !== id));
    } catch (err) { setError(err.message); }
  };

  const handleDeleteExpired = async () => {
    if (!confirm('Delete all expired opportunities across the platform?')) return;
    try {
      const res = await apiFetch('/api/admin/opportunities/expired', { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete expired');
      load();
    } catch (err) { setError(err.message); }
  };

  const downloadReport = () => {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const now = new Date();

  const total = opps.length;
  const active = opps.filter(o => o.status === "active").length;
  const closed = opps.filter(o => o.status === "closed").length;
  const expired = opps.filter(o => isExpired(o.deadline)).length;

  const jobs = opps.filter(o => o.category === "job").length;
  const internships = opps.filter(o => o.category === "internship").length;
  const scholarships = opps.filter(o => o.category === "scholarship").length;

  // =========================
  // Title
  // =========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("GLOBAL OPPORTUNITIES REPORT", 148, 18, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(
    `Generated on: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`,
    14,
    30
  );

  doc.setDrawColor(180);
  doc.line(14, 34, 283, 34);

  // =========================
  // Summary
  // =========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("SUMMARY", 14, 45);

  autoTable(doc, {
    startY: 50,
    theme: "grid",
    head: [["Metric", "Count"]],
    body: [
      ["Total Opportunities", total],
      ["Active", active],
      ["Closed", closed],
      ["Expired", expired],
      ["Jobs", jobs],
      ["Internships", internships],
      ["Scholarships", scholarships],
    ],
    headStyles: {
      fillColor: [30, 58, 138],
    },
    styles: {
      fontSize: 11,
    },
  });

  // =========================
  // Opportunity Details
  // =========================

  const rows = opps.map((o) => [
    o.title,
    o.organization_name,
    o.category,
    o.status,
    o.deadline
      ? new Date(o.deadline).toLocaleDateString()
      : "N/A",
  ]);

  const finalY = doc.lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("OPPORTUNITY DETAILS", 14, finalY);

  autoTable(doc, {
    startY: finalY + 5,
    theme: "striped",
    head: [[
      "Title",
      "Organization",
      "Category",
      "Status",
      "Deadline",
    ]],
    body: rows,
    styles: {
      fontSize: 9,
      cellPadding: 3,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },
  });

  // =========================
  // Footer
  // =========================

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setDrawColor(180);
    doc.line(14, 195, 283, 195);

    doc.setFontSize(9);

    doc.text(
      "Generated by Student Opportunities Management System",
      14,
      202
    );

    doc.text(
      `Page ${i} of ${pages}`,
      283,
      202,
      {
        align: "right",
      }
    );
  }

  const timestamp = now
    .toISOString()
    .replace(/:/g, "-")
    .replace("T", "_")
    .split(".")[0];

  doc.save(`Global_Opportunities_Report_${timestamp}.pdf`);
};

const downloadExcel = () => {
  const rows = opps.map((o) => ({
    Title: o.title,
    Organization: o.organization_name,
    Category: o.category,
    Status: o.status,
    Deadline: o.deadline
      ? new Date(o.deadline).toLocaleDateString()
      : "N/A",
    Expired: isExpired(o.deadline) ? "Yes" : "No",
  }));

  const worksheet = XLSX.utils.json_to_sheet(rows);

  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    "Global Opportunities"
  );

  const timestamp = new Date()
    .toISOString()
    .replace(/[:.]/g, "-");

  XLSX.writeFile(
    workbook,
    `Global_Opportunities_Report_${timestamp}.xlsx`
  );
};

  const isExpired = (deadline) => deadline && new Date(deadline) < new Date();

  return (
    <div style={{ fontFamily: 'var(--font-body-text), sans-serif' }}>
      <div
  style={{
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '32px',
    gap: '12px',
    flexWrap: 'wrap'
  }}
>
        <h1 style={{ fontSize: '28px', fontWeight: '700', color: 'var(--color-ink)', margin: '0 0 8px 0' }}>Global Opportunities</h1>
        <div style={{ display: 'flex', gap: '12px' }}>

  {opps.length > 0 && (
    <button
      onClick={() => setReportOpen(true)}
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        backgroundColor: '#1e3a8a',
        color: '#ffffff',
        border: 'none',
        padding: '10px 18px',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: '600',
        cursor: 'pointer',
        boxShadow: '0 4px 6px -1px rgba(30,58,138,0.2)',
        fontFamily: 'inherit',
      }}
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>

      Download Report
    </button>
  )}

  <ReportModal
  open={reportOpen}
  onClose={() => setReportOpen(false)}
  onPDF={downloadReport}
  onExcel={downloadExcel}
  title="Generate Opportunities Report"
/>

  </div>

  <button
    onClick={handleDeleteExpired}
    style={{
      backgroundColor: '#ffffff',
      color: '#dc2626',
      border: '1px solid var(--color-line)',
      padding: '10px 20px',
      borderRadius: '10px',
      fontSize: '13px',
      fontWeight: '600',
      cursor: 'pointer',
      fontFamily: 'inherit',
    }}
  >
    Delete all expired
  </button>

</div>
      
      {error && <p style={{ color: '#dc2626', fontWeight: '600', padding: '16px', backgroundColor: 'rgba(220,38,38,0.05)', borderRadius: '12px', marginBottom: '24px' }}>{error}</p>}
      
      <div style={{ backgroundColor: '#ffffff', borderRadius: '16px', border: '1px solid var(--color-line)', overflow: 'hidden', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.02)' }} className="table-scroll">
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', minWidth: '600px' }}>
          <thead style={{ backgroundColor: 'var(--color-paper)', borderBottom: '1px solid var(--color-line)' }}>
            <tr>
              {['Title', 'Organization', 'Category', 'Status', 'Deadline', ''].map(h => (
                <th key={h} style={{ padding: '16px 24px', fontSize: '11px', fontWeight: '700', color: 'var(--color-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {opps.length === 0 ? (
              <tr><td colSpan="6" style={{ padding: '48px', textAlign: 'center', color: 'var(--color-muted)', fontWeight: '500' }}>No opportunities found in the system.</td></tr>
            ) : opps.map((o) => (
              <tr key={o.id} style={{ borderBottom: '1px solid var(--color-line)' }}>
                <td style={{ padding: '16px 24px', fontSize: '14px', fontWeight: '600', color: 'var(--color-ink)' }}>{o.title}</td>
                <td style={{ padding: '16px 24px', fontSize: '14px', color: 'var(--color-muted)', fontWeight: '500' }}>{o.organization_name}</td>
                <td style={{ padding: '16px 24px', fontSize: '13px', color: 'var(--color-ink)', fontWeight: '600', textTransform: 'capitalize' }}>
                  <span style={{ backgroundColor: 'var(--color-paper)', padding: '4px 10px', borderRadius: '6px', border: '1px solid var(--color-line)' }}>{o.category}</span>
                </td>
                <td style={{ padding: '16px 24px', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em', color: o.status === 'active' ? '#15803d' : 'var(--color-muted)' }}>{o.status}</td>
                <td style={{ padding: '16px 24px', fontSize: '13px', fontWeight: '500', color: isExpired(o.deadline) ? '#dc2626' : 'var(--color-muted)' }}>
                  {o.deadline ? new Date(o.deadline).toLocaleDateString() : '—'}
                </td>
                <td style={{ padding: '16px 24px', textAlign: 'right' }}>
                  <button onClick={() => handleDelete(o.id)} style={{ background: 'none', border: 'none', color: '#dc2626', fontSize: '13px', fontWeight: '600', cursor: 'pointer', padding: '6px 12px', borderRadius: '6px', fontFamily: 'inherit' }} onMouseOver={e=>e.target.style.backgroundColor='rgba(220,38,38,0.1)'} onMouseOut={e=>e.target.style.backgroundColor='transparent'}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}